In [4]:
import pandas as pd
import numpy as np

In [165]:
dict={"Location":["United States","India","Brazil","Russia","United Kingdom"],"Cases":[28,11079979,10537473,84568527574592,57295797575279],"Deaths":[517204,156938,254263,86122,122705],"Recovered":["",10763451,9386440,3811797,""]}

In [166]:
df=pd.DataFrame(dict,index=["a","b","c","d","e"])

In [167]:
df

Location           Cases  Deaths Recovered
a   United States              28  517204          
b           India        11079979  156938  10763451
c          Brazil        10537473  254263   9386440
d          Russia  84568527574592   86122   3811797
e  United Kingdom  57295797575279  122705

In [168]:
dict=pd.DataFrame(dict,columns=["Location","Cases","Status"])

In [169]:
df

Location           Cases  Deaths Recovered
a   United States              28  517204          
b           India        11079979  156938  10763451
c          Brazil        10537473  254263   9386440
d          Russia  84568527574592   86122   3811797
e  United Kingdom  57295797575279  122705

In [170]:
# Define a function to determine the status based on the number of cases
def determine_status(row):
    if row['Cases'] < 3000000:
        return 'Low'
    elif 3000000 <= row['Cases'] < 4000000:
        return 'Medium'
    else:
        return 'High'

# Apply the function to create the new "Status" column
df['Status'] = df.apply(determine_status,axis=1)

In [171]:
df['Recovered'] = pd.to_numeric(df['Recovered'])

In [172]:
df["Deaths"].rank()

a    5.0
b    3.0
c    4.0
d    1.0
e    2.0
Name: Deaths, dtype: float64

In [173]:
df.count()

Location     5
Cases        5
Deaths       5
Recovered    3
Status       5
dtype: int64

In [174]:
df.describe()

Cases         Deaths     Recovered
count  5.000000e+00       5.000000  3.000000e+00
mean   2.837287e+13  227446.400000  7.987229e+06
std    4.002982e+13  173632.786487  3.680994e+06
min    2.800000e+01   86122.000000  3.811797e+06
25%    1.053747e+07  122705.000000  6.599118e+06
50%    1.107998e+07  156938.000000  9.386440e+06
75%    5.729580e+13  254263.000000  1.007495e+07
max    8.456853e+13  517204.000000  1.076345e+07

In [152]:
df.fillna({'Recovered': 0}, inplace=True)

In [153]:
df

Location           Cases  Deaths   Recovered Status
a   United States              28  517204         0.0    Low
b           India        11079979  156938  10763451.0   High
c          Brazil        10537473  254263   9386440.0   High
d          Russia  84568527574592   86122   3811797.0   High
e  United Kingdom  57295797575279  122705         0.0   High

In [154]:
df.min()

Location     Brazil
Cases            28
Deaths        86122
Recovered       0.0
Status         High
dtype: object

In [155]:
df.max()

Location      United States
Cases        84568527574592
Deaths               517204
Recovered        10763451.0
Status                  Low
dtype: object

In [156]:
np.argmin(df["Deaths"])

3

In [157]:
min_index = df['Cases'].idxmin()


In [158]:
min_index

'a'

In [159]:


# Assuming df is your DataFrame
kurtosis_values = df["Cases"].kurt()
print(kurtosis_values)


-1.8578762342437436


In [160]:
# Assuming df is your DataFrame
per_change= df["Cases"].pct_change()
print(per_change)


a             NaN
b    3.957125e+05
c   -4.896273e-02
d    8.025503e+06
e   -3.224927e-01
Name: Cases, dtype: float64


In [161]:
df['Recovered'].fillna(0, inplace=True)

C:\Users\SAAD COMMUNICATION\AppData\Local\Temp\ipykernel_9180\2162155955.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Recovered'].fillna(0, inplace=True)


In [162]:
df['Recovered'].head()

a           0.0
b    10763451.0
c     9386440.0
d     3811797.0
e           0.0
Name: Recovered, dtype: float64

In [163]:
recovered_mean = df['Recovered'].mean()

In [ ]:
df['Recovered'].fillna(recovered_mean, inplace=True)

In [5]:
s1=pd.Series([7,-5,7,4,2,0,4])

In [6]:
s1.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [7]:
s1.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [8]:
s1.rank(ascending="False",method="max")

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [31]:
array=np.random.randn(3,3)

In [32]:
array

array([[ 0.19950885, -0.13408704, -0.6715174 ],
       [ 0.11286222, -0.53598393, -0.48652454],
       [-1.41740713,  0.92193642, -1.1375107 ]])

In [33]:
array.ndim

2

In [34]:
array[::-1,::-1]

array([[-1.1375107 ,  0.92193642, -1.41740713],
       [-0.48652454, -0.53598393,  0.11286222],
       [-0.6715174 , -0.13408704,  0.19950885]])

In [35]:
array.T

array([[ 0.19950885,  0.11286222, -1.41740713],
       [-0.13408704, -0.53598393,  0.92193642],
       [-0.6715174 , -0.48652454, -1.1375107 ]])